// Package component contains helpers for talking to the Component custom
// resource (core.cs.sap.com/v1alpha1) served by the SAP component-operator,
// using the typed client generated by that project.
package component

import (
	componentv1alpha1 "github.com/sap/component-operator/api/v1alpha1"
	versioned "github.com/sap/component-operator/pkg/client/clientset/versioned"
	"k8s.io/cli-runtime/pkg/genericclioptions"
	"k8s.io/client-go/kubernetes"
)

// GroupVersionKind identifies the Component custom resource as served by the
// SAP component-operator. It is primarily used to stamp apiVersion/kind onto
// objects returned by the typed client (which strips them) before printing.
var GroupVersionKind = componentv1alpha1.GroupVersion.WithKind(componentv1alpha1.KindComponent)

// NewClientset builds the typed component-operator clientset from the given
// kubectl config flags.
func NewClientset(flags *genericclioptions.ConfigFlags) (*versioned.Clientset, error) {
	config, err := flags.ToRESTConfig()
	if err != nil {
		return nil, err
	}
	return versioned.NewForConfig(config)
}

// NewKubernetesClientset builds a core Kubernetes clientset from the given
// kubectl config flags (e.g. to read Events).
func NewKubernetesClientset(flags *genericclioptions.ConfigFlags) (*kubernetes.Clientset, error) {
	config, err := flags.ToRESTConfig()
	if err != nil {
		return nil, err
	}
	return kubernetes.NewForConfig(config)
}

// ResolveNamespace returns the namespace to operate in, honouring the
// --namespace flag and falling back to the namespace configured in the current
// kubeconfig context.
func ResolveNamespace(flags *genericclioptions.ConfigFlags) (string, error) {
	namespace, _, err := flags.ToRawKubeConfigLoader().Namespace()
	return namespace, err
}
